@startuml
skinparam style strictuml
skinparam SequenceMessageAlignment center

actor User
participant App
participant Server

User -> App: Nhấn nút 'Thay đổi thông tin tài khoản'
activate App
App -> Server: Yêu cầu truy cập vào dữ liệu tài khoản cá nhân
activate Server
Server --> App: Trả về dữ liệu tài khoản cá nhân
deactivate Server
App -> User: Hiển thị thông tin tài khoản cá nhân
User -> App: Chọn chức năng thay đổi thông tin
App -> User: Hiển thị form thay đổi thông tin
User -> App: Cung cấp thông tin cập nhật
App -> Server: Yêu cầu cập nhật thông tin tài khoản cá nhân
activate Server
Server --> App: Xác nhận cập nhật thành công
deactivate Server
App --> User: Hiển thị thông báo cập nhật thành công
deactivate App
@enduml
