@startuml Fundarasing Sequence
skinparam style strictuml
skinparam SequenceMessageAlignment center

participant User
participant View
participant Responsity
participant Server
participant Bank

activate View
User -> View : Nhấn đăng ký gây quỹ
View --> User : Hiển thị màn hình gây quỹ
deactivate View

activate User
User -> View: Điền thông tin liên quan để đăng ký gây quỹ
deactivate User

activate View
View -> View: Xác nhận thông tin đăng ký
View -> Responsity : Gửi thông tin
deactivate View

activate Responsity
Responsity -> Server: Gửi yêu cầu đăng ký
deactivate Responsity

activate Server
Server -> Bank : Gửi thông tin
deactivate Server

activate Bank
Bank -> Bank : Kiểm tra thông tin tài khoản
deactivate Bank

Bank --> Server: Trả về kết quả
Server --> Responsity: Trả về kết quả
Responsity --> View: Trả về kết quả
View --> User: Thông báo kết quả

@enduml