@startuml FundraisingSequence
skinparam style strictuml
skinparam SequenceMessageAlignment center

participant User
participant View
participant Responsity
participant Server
participant Bank

activate View
User -> View: Nhấn đăng ký gây quỹ
View --> User: Hiển thị màn hình gây quỹ
deactivate View

activate User
User -> View: Điền thông tin liên quan để đăng ký gây quỹ
deactivate User

activate View
View -> View: Xác nhận thông tin đăng ký
View -> Responsity: Gửi thông tin
deactivate View

activate Responsity
Responsity -> Server: Gửi yêu cầu đăng ký
deactivate Responsity

activate Server
alt Đăng ký thành công
    Server -> Bank: Gửi thông tin đăng ký
    deactivate Server

    activate Bank
    Bank -> Bank: Kiểm tra thông tin tài khoản
    deactivate Bank

    Bank --> Server: Trả về kết quả đăng ký thành công
    Server --> Responsity: Trả về kết quả đăng ký thành công
else Đăng ký thất bại
    Server -> Bank: Gửi thông tin đăng ký
    deactivate Server

    activate Bank
    Bank -> Bank: Kiểm tra thông tin tài khoản và thông báo lỗi
    deactivate Bank

    Bank --> Server: Trả về kết quả đăng ký thất bại
    Server --> Responsity: Trả về kết quả đăng ký thất bại
end

deactivate Responsity

Responsity --> View: Trả về kết quả
View --> User: Thông báo kết quả

@enduml
