@startuml DonateSequence
skinparam style strictuml
skinparam SequenceMessageAlignment center

participant User
participant View
participant Responsity
participant Server
participant Bank

activate View
User -> View: Nhấn button Donate
View --> User: Hiển thị màn hình chọn mức tiền ủng hộ
deactivate View

activate User
User -> View: Nhấn nút "Giao dịch qua ngân hàng"
deactivate User

activate View
View -> View: Xác nhận thông tin
View -> Responsity: Gửi thông tin đi
deactivate View

activate Responsity
Responsity -> Server: Gửi yêu cầu thanh toán
deactivate Responsity

activate Server
alt Thanh toán thành công
    Server -> Bank: Gửi thông tin thanh toán
    deactivate Server

    activate Bank
    Bank -> Bank: Kiểm tra tài khoản và thực hiện thanh toán
    deactivate Bank

    Bank --> Server: Trả về kết quả thanh toán thành công
    Server --> Responsity: Trả về kết quả thanh toán
else Thanh toán thất bại
    Server -> Bank: Gửi thông tin thanh toán
    deactivate Server

    activate Bank
    Bank -> Bank: Kiểm tra tài khoản và thông báo thanh toán thất bại
    deactivate Bank

    Bank --> Server: Trả về kết quả thanh toán thất bại
    Server --> Responsity: Trả về kết quả thanh toán thất bại
end

deactivate Responsity

Responsity --> View: Trả về kết quả
View --> User: Thông báo kết quả

@enduml
